### ISSUE TITLE
Modifications for Python versions less than 3.11

### ISSUE THREAD

**Issue by karthiks2611** [PandaRules/MySQL-Editor-Python#1]
This is for people who are using Python versions less than 3.11. I have tried this using Python 3.8.10 and Windows 11

Edit `backend.py` and remove `Self` from line 1 add this

`from typing_extensions import Self`

This is for those who are using Python version less than 3.11. 
Also don't forget to install `typing_extensions`

And also change in `session.py`
`def getSessionDetails(cls, session: str) -> tuple[str, str, int]:`

to 
`def getSessionDetails(cls, session: str)]:`

**Comment by PandaRules** [comment]
This was packaged on EndeavourOS, so I'd assume it used that system's glibc version

I will look into it tomorrow

**Comment by PandaRules** [comment]
Looking into it briefly, send like the compiled builds are only forward compatible, not backward, hence the error

**Comment by karthiks2611** [comment]
In WINE it doesn't start without errors

**Comment by PandaRules** [comment]
Looked into it, and I was right.
I would need to build on a system with an older GLibC version, something which I don't have access to, and trying to compile them in containers isn't working.

So until I can get access to a system with an older GLibC version, a minimum of 2.38 will be required.

**Comment by PandaRules** [comment]
The release on PyPI should fix this issue

**Comment by SudarshanSR** [comment]
I made the changes, can you check now?

**Comment by karthiks2611** [comment]
Yes, working perfectly. We can close this
